### ISSUE TITLE
提示：没有产品密钥时，需要将 DEV_DYN_REG_ENABLED 设置为 OFF，不然会导致读取产品密钥失败

### ISSUE THREAD

**Issue by alvis233** [tencentyun/qcloud-iot-explorer-sdk-embedded-c#12]
动态注册DEV_DYN_REG_ENABLED默认是开启的，编译之后会根据相关逻辑读取产品密钥，但是并非所有场景都有产品密钥；入门文档应该说明这点，提示开发者将 DEV_DYN_REG_ENABLED 设置为 OFF，不然会导致读取产品密钥失败

**Comment by Genie-bj** [comment]
你好，感谢指出，如果开发过程没有动态注册的需求，在开发前将动态注册功能通过CMakeLists.txt关闭掉即可。
