### ISSUE TITLE
协议栈内的文件操作，有操作系统强相关的接口

### ISSUE THREAD

**Issue by jiaotilizi** [tencentyun/qcloud-iot-explorer-sdk-embedded-c#3]
建议协议栈内的关于文件的操作，放到HAL层，屏蔽硬件差异：
（1）如dynreg.c文件内的_cert_file_save函数；
（2）log_upload.c文件内的_gen_key_from_file函数；
（3）gateway_common.c文件内的gen_key_from_cert_file函数。

**Comment by yougaliu007** [comment]
谢谢你的建议，v3.1.5版本已修改
