### ISSUE TITLE
freertos+lwip抽取出来的代码的时间获取存在问题

### ISSUE THREAD

**Issue by heyMiaomiao** [tencentyun/qcloud-iot-explorer-sdk-embedded-c#5]
尝试将子设备绑定到网关时提示-805，QCLOUD_ERR_BIND_SIGN_EXPIRED。签名过期。

DBG|2020-10-30 14:57:31|mqtt_client_publish.c|qcloud_iot_mqtt_publish(345): publish packetID=0|topicName=$gateway/operation/W5IGBL8VM0/SMARTGATEWAY0001|payload={"type":"bind","payload":{"devices":[{"product_id":"05JJPYJVPK","device_name":"010039680923","signature":"eLfJnaTSTLi3d+iY60QhQ7VxuPs=","random":1484600710,"timestamp":2018249,"signmethod":"hmacsha1","authtype":"psk"}]}}

发现uint32_t HAL_GetTimeMs(void)获取毫秒的函数返回居然是个32位数。

将返回改成uint64_t 然后各种错误。希望解决一下。

**Comment by yougaliu007** [comment]
网关绑定接口依赖准确的UTC时间，请正确适配 HAL_Timer_current_sec
