### ISSUE TITLE
Windows环境下编译执行网关协议会报错

### ISSUE THREAD

**Issue by wenkumk** [tencentyun/qcloud-iot-explorer-sdk-embedded-c#8]
![image](https://user-images.githubusercontent.com/35908729/112245031-11da8680-8c48-11eb-9de8-143f848f1df1.png)
![image](https://user-images.githubusercontent.com/35908729/112245077-23bc2980-8c48-11eb-855a-356291bd3c4b.png)
这是为什么呢？

**Comment by xupenghu** [comment]
新版本修复了，请更新版本使用
