### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Ca2OH4** [tencentyun/qcloud-iot-explorer-sdk-embedded-c#9]
/Users/admin/iot/qcloud-iot-explorer-sdk-embedded-c-master/platform/os/linux/HAL_Timer_linux.c:35:5: error: member reference base type 'uintptr_t' (aka 'unsigned long') is not a structure or union

**Comment by LintP** [comment]
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by xupenghu** [comment]
fixed it
